apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-pep
  labels:
    type: local
spec:
  storageClassName: proxy
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/certs/"