apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pep-iot-agent
  name: pep-iot-agent
spec:
  ports:
    - name: "pep"
      port: 8050
      targetPort: 8050
  selector:
    io.kompose.service: pep-iot-agent
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pep-iot-agent
  name: pep-iot-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pep-iot-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/main: "true"
        io.kompose.service: pep-iot-agent
    spec:
      containers:
        - env:
            - name: DEBUG
              value: pep-proxy:*
            - name: PEP_PASSWORD
              value: pep_proxy_95424dd3-b758-4ff7-9be1-d279426316e5
            - name: PEP_PROXY_APP_HOST
              value: cloud-agent
            - name: PEP_PROXY_APP_ID
              value: daf272a2-d2c0-4b39-9951-1ce5fc05fa83
            - name: PEP_PROXY_APP_PORT
              value: "8880"
            - name: PEP_PROXY_APP_SSL_ENABLED
              value: "false"
            - name: PEP_PROXY_AUTH_ENABLED
              value: "true"
            - name: PEP_PROXY_HTTPS_ENABLED
              value: "true"
            - name: PEP_PROXY_HTTPS_PORT
              value: "8050"
            - name: PEP_PROXY_IDM_HOST
              value: fiware-keyrock
            - name: PEP_PROXY_IDM_PORT
              value: "3443"
            - name: PEP_PROXY_IDM_SSL_ENABLED
              value: "true"
            - name: PEP_PROXY_MAGIC_KEY
              value: sco
            - name: PEP_PROXY_PDP
              value: idm
            # - name: PEP_PROXY_PORT
            #   value: "8050"
            - name: PEP_PROXY_USERNAME
              value: pep_proxy_f698863d-892d-459e-8ab1-e01fb97fc8da
          image: fiware/pep-proxy:7.8.2
          name: pep-iot-agent
          ports:
            - containerPort: 8050
          resources: {}
          volumeMounts:
            - mountPath: /opt/fiware-pep-proxy/cert
              name: pep-iot-agent-claim0
      restartPolicy: Always
      volumes:
        - name: pep-iot-agent-claim0
          persistentVolumeClaim:
            claimName: pep-iot-agent-claim0
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pep-iot-agent-claim0
spec:
  storageClassName: proxy
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi