apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: cluster-role-security
subjects:
- kind: User
  name: warmachine 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: security
  apiGroup: rbac.authorization.k8s.io
