apiVersion: v1
kind: Service
metadata:
  name: mysql-keyrock
  labels:
    type: keyrock
    tier: db
spec:
  selector:
    type: keyrock
    tier: db
  type: NodePort  
  ports:
    - port: 3306
      nodePort: 30307

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-keyrock
spec:
  selector:
    matchLabels:
      type: keyrock
      tier: db
  serviceName: "mysql-keyrock"
  replicas: 1
  template:
    metadata:
      labels:
        type: keyrock
        tier: db
    spec:
      containers:
        - name: mysql
          image: mariadb:latest
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: keyrock-secrets
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: keyrock-mysql-persistent-storage-claim
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: keyrock-mysql-persistent-storage-claim
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi

