apiVersion: v1
kind: Service
metadata:
  name: mysql-tfm
  labels:
    type: tfm
    tier: db
spec:
  selector:
    type: tfm
    tier: db
  type: NodePort  
  ports:
    - port: 3306
      nodePort: 30306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-tfm
spec:
  selector:
    matchLabels:
      type: tfm
      tier: db
  serviceName: "mysql-tfm"
  replicas: 1
  template:
    metadata:
      labels:
        type: tfm
        tier: db
    spec:
      containers:
        - name: mysql
          image: mariadb:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: tfm
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: tfm-mysql-persistent-storage-claim
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: tfm-mysql-persistent-storage-claim
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi

