apiVersion: v1
kind: Service
metadata:
  name: cloud-agent
spec:
  type: NodePort #NodePort
  selector:
    type: cloud
    tier: agent
  ports:
    - port: 8880
      nodePort: 30880
      name: agent
      targetPort: 8880
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      type: cloud
      tier: agent
  template:
    metadata:
      labels:
        type: cloud
        tier: agent
    spec:
      containers:
        - name: cloud-agent
          image: cloud-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8880
          env:
          - name: FIWARE_HOST
            value: orion
          - name: FIWARE_PORT
            value: '1026'